on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: octocat-hello-action # workflow file can reside in same repo as actions for initial testing
      with:
        who-to-greet: 'Mundo'
      id: hello
    - run: echo "The time was ${{ steps.hello.outputs.time }}"